package(default_visibility = ["//visibility:public"])

config_setting(
  name = "debug",
  values = {
    "define": "config=debug",
  },
)

config_setting(
  name = "release",
  values = {
    "define": "config=release",
  },
)

config_setting(
  name = "qa",
  values = {
    "define": "config=qa",
  },
)